lib/open_api_spex/plug/cast.ex

add exception raising for improper use of OpenApiSpex.Plug.Cast

Fix inifinite recursion in OpenApiSpex.Plug.Cast

---

lib/open_api_spex/operation.ex
lib/open_api_spex/schema.ex
lib/open_api_spex/schema_helper.ex
test/schema_test.exs
test/support/schemas.ex

Created new branch for PR so that formatting is separate PR from this.

Type check validation on schema

---

lib/open_api_spex/schema.ex
test/schema_test.exs

Given:
```elixir
iex(1)> alias OpenApiSpex.Schema
OpenApiSpex.Schema
iex(2)> schema = %Schema{
...(2)>         type: :integer,
...(2)>         minimum: -1,
...(2)>         maximum: 1,
...(2)>         exclusiveMinimum: true,
...(2)>         exclusiveMaximum: true
...(2)>       }
%OpenApiSpex.Schema{
maxLength: nil,
maxProperties: nil,
minimum: -1,
minProperties: nil,
maxItems: nil,
exclusiveMaximum: true,
example: nil,
externalDocs: nil,
pattern: nil,
"x-struct": nil,
description: nil,
oneOf: nil,
anyOf: nil,
format: nil,
required: nil,
properties: nil,
enum: nil,
default: nil,
maximum: 1,
minItems: nil,
minLength: nil,
nullable: nil,
multipleOf: nil,
discriminator: nil,
allOf: nil,
title: nil,
type: :integer,
writeOnly: nil,
uniqueItems: nil,
xml: nil,
items: nil,
readOnly: nil, …
```

Make exclusive minimum exclusive maximum work

---

lib/open_api_spex/cast/string.ex
test/cast/string_test.exs

After much debate we have a PR that addresses issue #90

OpenApiSpex.Cast.String.cast/1 should return dates or date-times 

---

README.md
examples/phoenix_app/lib/phoenix_app_web/api_spec.ex
examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller.ex
examples/plug_app/lib/plug_app/api_spec.ex
lib/open_api_spex/open_api.ex
lib/open_api_spex/plug/put_api_spec.ex
test/operation2_test.exs
test/support/api_spec.ex

Add behaviour to OpenApi module documenting the `spec/0` callback.

---

README.md

Fix documentation to safely generate atom in open_api_operation

---

lib/open_api_spex/cast/error.ex
lib/open_api_spex/cast/object.ex
test/cast/object_test.exs

check_min_properties function and appropriate error handling and unit test added.

Object.cast calls check_min_properties now

---

lib/open_api_spex.ex
lib/open_api_spex/cast/all_of.ex
lib/open_api_spex/cast/any_of.ex
lib/open_api_spex/cast/object.ex
lib/open_api_spex/cast/one_of.ex
lib/open_api_spex/components.ex
lib/open_api_spex/reference.ex
lib/open_api_spex/schema.ex
test/cast/all_of_test.exs
test/cast/one_of_test.exs
test/schema_test.exs

This is PR https://github.com/open-api-spex/open_api_spex/pull/143, with additional fixes.

Fix casting/validating of oneOf, anyOf

---

lib/open_api_spex/operation.ex

Fixes type specs to resolve Dialyzer issue found in build: https://travis-ci.com/open-api-spex/open_api_spex/jobs/243740256

ExDoc branch: Fix dialyzer

---

lib/open_api_spex/cast/all_of.ex
test/cast/all_of_test.exs

This is kind of a follow up of #134. 
We had some issues with the parsing of allOf Schemas. This PR should fix most of those issues.
I've also added some tests to make my point more clear of whats currently not working.

Fixes allOf definitions for multi-typed allOf array and complex structs with inheritance

---

README.md
lib/open_api_spex/controller.ex
lib/open_api_spex/operation.ex
lib/open_api_spex/path_item.ex
lib/open_api_spex/schema_resolver.ex
test/controller_test.exs
test/support/user_controller_annotated.ex

Experimental spec API described in #76
Also: Allow partially specified controller

ExDocs based spec generation

---

lib/open_api_spex/cast/all_of.ex
test/cast/all_of_test.exs

Fixes regression introduced in #161

Fixes casting of allOf for schema with x-struct

---

lib/open_api_spex/test/test_assertions.ex
test/schema_test.exs
test/support/api_spec.ex
test/support/schemas.ex

Closes #154
I had a similar problem verifying if a value matches a schema when the value is not an object.

Accept any term to be verified against a schema

---

CHANGELOG.md
README.md
mix.exs

Version 3.5.1

---

CHANGELOG.md
CONTRIBUTING.md
README.md
lib/open_api_spex/controller.ex
mix.exs

Version 3.5.2

---

lib/open_api_spex/cast/array.ex
lib/open_api_spex/cast/error.ex
test/cast/array_test.exs
test/cast/error_test.exs

This PR contains fixes for https://github.com/open-api-spex/open_api_spex/issues/179

Fix empty array minItems validation and error messages

---

lib/open_api_spex/schema_resolver.ex

Resolve schema modules from Response in Components

---

lib/open_api_spex/cast/discriminator.ex
lib/open_api_spex/cast_parameters.ex
test/plug/cast_test.exs
test/support/pet_controller.ex
test/support/router.ex
test/support/schemas.ex

This addresses the issues reported in #199

Fixes #199

---

lib/open_api_spex/cast/string.ex

Fixes errors in parameter pattern validation

---

lib/open_api_spex/cast/object.ex
test/cast/object_test.exs

As discussed in #207 this PR implements the casting the additional params into plain maps using a schema.

implements casting additional properties using a provided schema

---

examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller.ex

Fix call to parameter/5 in example app

---

CHANGELOG.md
README.md
mix.exs

Pardon the massive formatting changes to the Changelog. My Prettier editor plugin did that automatically. I can revert those changes back if necessary.

Version 3.7.0

---

lib/open_api_spex/schema.ex
lib/open_api_spex/schema_resolver.ex
test/schema_resolver_test.exs
test/schema_test.exs

More informative errors for bad schema

---

lib/open_api_spex/schema.ex

Correction of little spelling error in the documentation.

Fixed the word 'Scheam' to 'Schema'

---

README.md

Updates a few links, adds some ``, and adds a period.

Small update on README.md

---

lib/open_api_spex/controller_specs.ex
lib/open_api_spex/operation_builder.ex

Allow top level security to apply to operations

---

lib/open_api_spex/controller_specs.ex
lib/open_api_spex/schema_resolver.ex
test/schema_resolver_test.exs
test/support/dsl_controller.ex
test/support/schemas.ex

This PR resolves schema modules for a band of callbacks on an operation. This should fix issue #127.

Add callback support to operation_spec

---

lib/open_api_spex/cast_parameters.ex
test/cast_parameters_test.exs

Resolves raised error described in comment https://github.com/open-api-spex/open_api_spex/issues/349#issuecomment-823678953

Allow casting params where parameter.content schema is a Reference

---

lib/open_api_spex/cast_parameters.ex
test/cast_parameters_test.exs

test for cast of query parameters with style: form and explode: false

---

lib/open_api_spex/cast/object.ex
test/cast/object_test.exs

When properties are set to `nil`

Fix casting additionalProperties

---

examples/phoenix_app/README.md
examples/plug_app/README.md

This pull request solve issue #396

Solve Issue #396

---

lib/open_api_spex/open_api/decode.ex

consider one-shot additionalProperties in .decode()

---

lib/open_api_spex/controller_specs.ex
lib/open_api_spex/extendable.ex
lib/open_api_spex/operation.ex
lib/open_api_spex/parameter.ex
lib/open_api_spex/path_item.ex
lib/open_api_spex/response.ex
lib/open_api_spex/security_scheme.ex
lib/open_api_spex/tag.ex
test/controller_specs_test.exs
test/support/dsl_controller.ex

See https://swagger.io/docs/specification/openapi-extensions/
Fix #342

Implement Extendable protocol for all structs that can have extensions

---

lib/open_api_spex/plug/swagger_ui.ex

See: https://github.com/open-api-spex/open_api_spex/issues/421

Bump swagger_ui version to 4.6.2

---

lib/mix/tasks/openapi.spec.json.ex
lib/open_api_spex/open_api.ex

Fixes the failing build: https://github.com/open-api-spex/open_api_spex/actions/runs/2299224747

Format code with mix format

---

lib/open_api_spex.ex
test/cast/all_of_test.exs

See: https://github.com/open-api-spex/open_api_spex/issues/432

Make OpenApiSpex.resolve_schema/2 work with schema modules

---

lib/open_api_spex/cast/discriminator.ex
test/cast/discriminator_test.exs

Fix casting non-objects against discriminator #551

---

lib/open_api_spex/plug/cast_and_validate.ex

resolves https://github.com/open-api-spex/open_api_spex/issues/588

Add notice that body params are not merged into Conn.params whne using cast and validate plug

---

lib/open_api_spex/cast/number.ex
test/cast/number_test.exs

fix: cast numbers as floats
