- lib/open_api_spex/schema.ex
Hi,
Not sure whether this is necessary as I'm not very familiar with Swagger. But I found by default, all the models contain `additionalProperties: true` in the Swagger UI:
I have to then pass in `additionalProperties: nil` to every single `%Schema{}` to get rid of them.
This PR sets `additionalProperties` to `nil` by default.
> Set `additionalProperties` to `nil` by default

- lib/open_api_spex/operation.ex
* requestBody is now defined as single object instead of a list of objects
* as defined in https://swagger.io/specification/#operationObject
Hello @mbuhot ,
i found a bug in the operation type spec and fixed it.
Greetings, Thomas
> operation typespec fixed (requestBody)

- lib/open_api_spex/components.ex
- lib/open_api_spex/open_api.ex
- lib/open_api_spex/security_scheme.ex
* in open_api, components and security_scheme structs to be nil
* as defined in https://swagger.io/specification
Hey @mbuhot ,
i updated the spec as we discussed in #18. I only updated the security scheme struct and the parents structs it belongs to. 
I guess there might be some more non-required fields in other specs that arent 100% in sync. But for now i only updated the ones i needed right now.
Greetings, Thomas
> allowing non required fields in Components to be nil

- lib/open_api_spex/schema.ex
- test/schema_test.exs
- test/support/router.ex
- test/support/schemas.ex
- test/support/user_controller.ex
Modified version of #13
differences are:
- `properties` is `nil` by default, since I don't think it makes sense to define a properties map for types other than `object`. 
- `additionalProperties` only causes a `cast` error if it is explicitly set to `false`. From what I can tell, this is the default behaviour of JSON-Schema which swagger schemas are based on.
@mennanov  What do you think?
> Fail cast when additionalProperties not allowed

- lib/open_api_spex/contact.ex
- lib/open_api_spex/discriminator.ex
- lib/open_api_spex/encoding.ex
- lib/open_api_spex/example.ex
- lib/open_api_spex/external_documentation.ex
- lib/open_api_spex/header.ex
- lib/open_api_spex/license.ex
- lib/open_api_spex/link.ex
- lib/open_api_spex/media_type.ex
- lib/open_api_spex/oauth_flow.ex
- lib/open_api_spex/oauth_flows.ex
- lib/open_api_spex/operation.ex
- lib/open_api_spex/parameter.ex
- lib/open_api_spex/path_item.ex
- lib/open_api_spex/reference.ex
- lib/open_api_spex/request_body.ex
- lib/open_api_spex/response.ex
- lib/open_api_spex/responses.ex
- lib/open_api_spex/schema.ex
- lib/open_api_spex/security_scheme.ex
- lib/open_api_spex/server.ex
- lib/open_api_spex/server_variable.ex
- lib/open_api_spex/tag.ex
- lib/open_api_spex/xml.ex
- test/schema_resolver_test.exs
Update struct and type definitions to match https://swagger.io/specification/
Required fields are enforced with `@enforce_keys`
Optional fields are typed as `something | nil`
@ThomasRueckert would you mind taking a look over these changes and let me know if it breaks your code?
> Update types and @enforce_keys for optional/required fields

- lib/open_api_spex/schema_resolver.ex
Since the `Operation.t()` data type allows request_body and parameters items to be also `Reference.t()` this case should be handled in respective `resolve_schema_modules_from_xxx` functions.
> correctly reslove `Reference` in parameter and request_body

- lib/open_api_spex/schema.ex
This is wrong because a schema can also contain only a `oneOf` property, no need of always have `type`
Fixes #27
> remove `:type` from `Schema` struct `@enforce_keys`

- CHANGELOG.md
- README.md
- lib/open_api_spex.ex
- lib/open_api_spex/discriminator.ex
- lib/open_api_spex/schema.ex
- lib/open_api_spex/test/assertions.ex
- mix.exs
- test/schema_test.exs
- test/support/api_spec.ex
- test/support/schemas.ex
Proof of concept support for casting polymorphic schemas using `discriminator` / `allOf`
@maxmellen I'd appreciate if you could take a look over this branch and see if you'd like to expand support for `oneOf` / `allOf`.
I'm not 100% happy with the `tag` / `untag` functions, but I couldn't come up with a cleaner way to prevent infinite recursion.
The biggest limitation now is that the struct types declared with the `OpenApiSpex.schema` macro don't contain any fields. The macro only looks at the `properties` key.  It should be possible to merge all the properties for schemas appearing in `allOf`.
> polymorphic cast

- lib/open_api_spex/schema.ex
- test/schema_test.exs
Hi there,
thanks for the nice framework.
While using the enum with strings I realised that the verification is not implemented yet. This change adds verification for strings when the enum options is given. Casting will fail if the value is not one of the given options.
> Handle enum for string values

- lib/open_api_spex/parameter.ex
Change `:deep` to `:deepObject`
according to https://swagger.io/docs/specification/describing-parameters/#query-parameters
> Fix parameter style

- lib/open_api_spex/plug/cast.ex
- lib/open_api_spex/plug/default_render_error.ex
- lib/open_api_spex/plug/validate.ex
- test/param_test.exs
- test/support/custom_error_user_controller.ex
- test/support/router.ex
With this PR you can overwrite the existing error response with a custom response:
```
defmodule MyAppWeb.UserController do
use Phoenix.Controller
plug OpenApiSpex.Plug.Cast,
render_error: MyApp.RenderError
plug OpenApiSpex.Plug.Validate,
render_error: MyApp.RenderError
...
end
defmodule MyApp.RenderError do
def init(opts), do: opts
def call(conn, reason) do
msg = %{error: reason} |> Posion.encode!()
conn
|> Conn.put_resp_content_type("application/json")
|> Conn.send_resp(400, msg)
end
end
```
> Make error response configurable

- README.md
- lib/open_api_spex.ex
- lib/open_api_spex/operation.ex
- lib/open_api_spex/plug/cast.ex
- test/open_api_spex_test.exs
- test/param_test.exs
- test/support/router.ex
- test/support/schemas.ex
- test/support/user_controller.ex
This change is motivated by the unintuitive behaviour of
merging the cast request body with the query/path params
into a single struct.
Matching on such a struct produces a compile error.
Since `Plug.Conn` already has a field to store `body_params`,
we use that to hold the cast requestBody.
matching on the requestBody in a controller now requires:
```elixir
def create(conn = %{body_params: %SomeType{}}, other_params = %{}) do
...
end
```
> Cast and validate body_params separately

- .travis.yml
- lib/open_api_spex/operation.ex
Fixes compiler warning:
```
warning: variable "params" is unused
lib/open_api_spex/operation.ex:202
```
Also adjusts Travis to fail the build when there is a compiler warning.
> Fix compiler warning

- lib/open_api_spex/schema.ex
- test/open_api_spex_test.exs
- test/schema_test.exs
- Validate enums of non-string types
- Validate anyOf/oneOf/allOf/not before type testing
- Improve error message for regex validations
> Incorporate improvements from #42

- test/schema_test.exs
Clean up test before adding more tests for `cast/3`:
- Wrap `schema/1` tests in a dedicated `"describe"` block.
- Wrap `cast/3` tests in a dedicated `"describe"` block.
> Clean up schema_test.exs

- lib/open_api_spex/schema.ex
- test/schema_test.exs
Fixes raised exception, `** (MatchError) no match of right hand side value: {:ok, []}` in `cast/3`, when wrong type is encountered for an object type. Also adds testing around handling unexpected type for array.
Question: When `nil` is the given value for an object type, should `cast/3` return an error, or should it return an ok? If ok, should it cast the `nil` to a `%{}`? This PR changes the behavior for that case from returning ok to returning an error.
> Resolve raised exception; return error tuple instead

- lib/open_api_spex/schema.ex
- test/schema_test.exs
Following up from #63, I've added a few new tests for cases where `Schema.cast/3` is called with invalid data types.
Several cases would previously have silently passed through data without conversion to the expected type.
> Error when unable to cast to expected type

- lib/open_api_spex/cast/primitive.ex
- test/cast/primitive_test.exs
The == comparison was converting the result and giving a false positive
on the tests.
> Fix number casting

- lib/open_api_spex/plug/swagger_ui.ex
- test/plug/swagger_ui_test.exs
This small change allows using Swagger UI for CSRF-protected APIs
> Send Plug CSRF token as x-csrf-token header

- lib/open_api_spex/plug/put_api_spec.ex
OTP 21.2 introduces :persistent_term which is vastly more efficient and performant compared to `Application.get_env/2`. Application env vars are backed in `:ets` which copies the value on lookup. Currently, the spec is stored in the env and retrieved on every call to the plug. We should therefore see a large performance improvement in memory footprint and some slight speed improvements.
The generated open api spec can be several orders of magnitude larger than the size of the conn object in our experience. Since the value of lookup is copied on each call to the plug, concurrent space complexity in the case of using `:application.get_env/2` is `O(n)` for both the conn map and the spec map since the spec is fetched on each connection.
The value returned by `:persistent_term.get/1` is only …
> Cache spec as a persistent term

- lib/open_api_spex/schema.ex
- test/schema_test.exs
Follow up on #81, casting of numbers was wrong in the previous cast api as well
> Fix casting of integer to float

- lib/open_api_spex/plug/cast2.ex
- lib/open_api_spex/plug/cast_and_validate.ex
- Move implementation of `Plug.Cast2` to `Plug.CastAndValidate`.
- Add module documentation for `Plug.CastAndValidate`.
This is an API change to make way for a new section I'd like to add to the project README. The new README section would guide the user on casting and validating requests using the new "cast and validate" plug (formerly `Cast2`, now `CastAndValidate`).
I didn't want to create public documentation on a module whose name was temporary. With a permanent name, users of the newer plug don't have to adjust their code once the new pattern becomes the preferred pattern.
Also, this work got me thinking about a related problem, #87.
> Deprecate Plug.Cast2, in favor of Plug.CastAndValidate

- README.md
- lib/open_api_spex/cast.ex
- lib/open_api_spex/open_api.ex
- lib/open_api_spex/operation2.ex
- lib/open_api_spex/plug/cast_and_validate.ex
- lib/open_api_spex/plug/json_render_error.ex
- test/cast_test.exs
- Makes CastAndValidate the canonical usage pattern
- Fixes runtime error for default error handler
- By default, uses application/json for error response
- Add guide for casting/validating outside of request/response cycle
> Cast and validate guide

- lib/open_api_spex/cast/error.ex
- lib/open_api_spex/cast/integer.ex
- test/cast/integer_test.exs
According to [Json Specs](https://json-schema.org/understanding-json-schema/reference/numeric.html#range) maximum and minimum (with and without comparison) are incorrect.
This PR fixes the comparison, tests and also verifies error message.
> Fix maximum and minimum error handling

- lib/open_api_spex/schema_resolver.ex
- test/schema_resolver_test.exs
Existing code was only resolving schemas when the response itself
was a schema reference, not an inline schema.
Now in-line schemas in responses will be treated the same as
schemas defined in the components.schemas section of the API spec.
Resolves #77
> Resolve schema references within in-line response schemas

- lib/open_api_spex/cast/integer.ex
- test/operation2_test.exs
Hi @mbuhot,
first let me thank you for keep this project running.
I noticed that the range for an integer query param isn't validated.
I wrote a failing test to make it clear what I mean.
Can you confirm?
Cheers.
> Missing validation for integer range on query params

- lib/open_api_spex/cast.ex
- lib/open_api_spex/cast/enum.ex
- test/cast/enum_test.exs
- test/cast_test.exs
Resolves #60 
Main changes in this PR are:
- Supports casting a simple string to an atom in enum list
- Supports casting a string-keyed map to atom keyed map in enum list
- Add tests for casting string keyed map to schema struct in enum list (was already supported by existing code)
Casting from a string keyed map to a struct enum without an explicit object schema is disallowed - if a struct is required, then a schema should be defined.
> Convert string to atom when casting enum schema

- lib/open_api_spex/plug/cache.ex
- lib/open_api_spex/plug/cast_and_validate.ex
- lib/open_api_spex/plug/put_api_spec.ex
This optimization avoids having to call `controller.open_api_operation(action)`
in each call to `CastAndValidate` for phoenix controllers.
The caching behaviour is moved into a separate module `OpenApiSpex.Plug.Cache`, and
updated from` CastAndValidate` the first time a phoenix controller/action
is used to resolve an Operation.
With this optimization in place, it becomes reasonable to use the `@doc` based `Operation` definitions accessed with `Code.fetch_docs/1` at runtime.
> Add operation lookup by phoenix {controller, action}

- lib/open_api_spex/extendable.ex
- lib/open_api_spex/info.ex
- lib/open_api_spex/open_api.ex
- test/encode_test.exs
This allows specify [extensions](https://swagger.io/specification/#specificationExtensions).
One of the useful cases could be setting up `x-logo` for [redoc](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-logo)
> Add extensions field inside of Info object

- README.md
> Fix typo in Validate Examples section of README.md

- lib/open_api_spex/extendable.ex
- lib/open_api_spex/open_api.ex
- test/encode_test.exs
This allows specify [extensions](https://swagger.io/specification/#specificationExtensions).
One of the useful cases could be setting up `x-tagGroups` for [redoc](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-tagGroups)
> Add extensions field inside of root object

- lib/open_api_spex/open_api.ex
- lib/open_api_spex/server.ex
- test/server_test.exs
- test/support/endpoint.ex
Addresses #110
* Removed `Server.from_endpoint/2` as opts for opt_app no required.
* `Endpoint.url/0` does not append :path, therefore `Endpoint.struct_url/0` used.
Does the Server URL need to have the path appended?  If not `Endpoint.url/0` can be used directly.
This patch will enable better support for Endpoints which perform runtime configuration within the `Endpoint.init/2` callback, where host, port, path etc may not be present within mix config that was relied upon by `Server.from_endpoint/2`.
> Added Server.from_endpoint/1 which obtains url (including :path) directly from Endpoint

- lib/open_api_spex.ex
- test/schema_construction_test.exs
Functions that dynamically construct a Schema can have their result passed
as-is to OpenApiSpex.schema without doing Map.from_struct. The change is to
Map.delete the __struct__ atom - which will do nothing on map and convert a
struct to map otherwise.
> Allow OpenApiSpex.schema() to take struct

- lib/open_api_spex/operation.ex
- lib/open_api_spex/path_item.ex
- test/operation_test.exs
Phoenix 1.4.7 changed `Phoenix.Router.Route` key `opts` to `plug_opts`.
https://github.com/phoenixframework/phoenix/commit/73949e7a47dad8ed427fc49ab0f1a431f70d6351
This patch addresses the issue caused when open_api_spex constructs an Operation struct from the route, specifically the plug and opts specified in the given route.  I have added tests to cover the new functionality.
I would suggest however that some thought be put into generic, early extraction of the keys from the route struct.  I think have a pop at this I think.
The Phoenix 1.4.7 release will raise this issue with users of this library due to the internal API dependency, so I pushed this patch quickly.
> Add support for phoenix 1.4.7 route.plug_opts

- lib/open_api_spex/schema.ex
- test/schema_test.exs
- test/support/api_spec.ex
- test/support/schemas.ex
There is an ability to set default value for a schema.
According to the specification:
The default value represents what would be assumed by the consumer
of the input as the value of the schema if one is not provided.
With the changes of this commit default value will be used when build Elixir structure.
> Use default from schema when build Elixir structure

- .travis.yml
- mix.exs
Travis matrix now includes elixir 1.7-1.9 and OTP 20 - 22
> Update minimum elixir version to 1.7

- lib/open_api_spex/cast/string.ex
- lib/open_api_spex/schema.ex
- mix.exs
- test/cast/string_test.exs
Replaces #121, #122.
The Open API docs describe how file uploads can be represented in an Open API schema:
https://swagger.io/docs/specification/describing-request-body/file-upload/
This PR lets open_api_spex support file uploads in the manner described by the docs.
> Cast upload

- lib/open_api_spex.ex
- lib/open_api_spex/cast_parameters.ex
- lib/open_api_spex/discriminator.ex
- lib/open_api_spex/operation2.ex
- lib/open_api_spex/parameter.ex
- lib/open_api_spex/reference.ex
- lib/open_api_spex/schema.ex
- test/operation2_test.exs
This PR enables usage of **%Reference{}** in operation definition in a Phoenix controller:
```
plug(OpenApiSpex.Plug.CastAndValidate)
def some_operation do
%Operation{
parameters: %Reference{"$ref": "#/components/parameters/some_param"},
...
}
end
```
assuming in the API SPEC it reads:
```
def spec do
%OpenApi{
....
components: %OpenApiSpex.Components{
parameters: %{
"some_param" =>
Operation.parameter(:some_param, :query, :string, "Some parameter")
...
```
Without this PR, CastAndValidate plug would crash when stepping on "$ref" in parameters.
> Support "$ref" in operation's parameters

- lib/open_api_spex/plug/swagger_ui.ex
This PR adds a new configuration option to `OpenApiSpex.Plug.SwaggerUI` to toggle `displayOperationId` on/off (defaults to off).
Accepting additional configuration options required changing the format of `init/1`, and I'm not sure my implementation captures the original intent of requiring `path` to be set, so please feel free to refactor.
> add `display_operation_id` option

- lib/open_api_spex/open_api.ex
- test/encode_test.exs
This PR prevents the nil fields in examples (Schema, MediaType, Example) from being removed during the JSON encoding.  
#141
> Keep examples' null fields

- lib/open_api_spex.ex
- lib/open_api_spex/schema_consistency.ex
- test/schema_consistency_test.exs
Prints compile-time warnings whenever an inconsistent schema is detected.
This PR comes with just one consistency check: `type: :object`.
Whenever the validation fails, the user will see a compile-time error, and the stack trace will point to the invalid schema definition:
```
warning: Inconsistent schema: :properties provided, but :type is missing or nil (expected :object)
lib/schemas.ex:23: UserSchema (module)
```
> Fixes #144 - makes sure proper Schema type provided if :properties key is present

- lib/open_api_spex/test/assertions2.ex
In asserting data against a schema, the error message for failures now shows the path into the data, for better debugging.
Before, it was very difficult to determine what in the input value didn't match with the schema.
> Improve reporting of assertion failures

- lib/open_api_spex/controller.ex
- lib/open_api_spex/path_item.ex
- lib/open_api_spex/schema_resolver.ex
- test/controller_test.exs
- test/support/user_controller_annotated.ex
This is basic support for documenting endpoints via ExDocs tags and documentation
strings. This introduces support for:
- `summary`
- `description`
- `requestBody`
- `parameters`
- `responses`
- `tags`
Close #76
> ExDocs based documentation generation

- lib/open_api_spex/cast/object.ex
- lib/open_api_spex/cast_parameters.ex
- test/cast/object_test.exs
- test/operation2_test.exs
This PR add support for `default` in the parameter's schema:
https://swagger.io/docs/specification/describing-parameters/#default
The implementation is a bit naive - I left an open question in the code.
> Apply defaults when casting the request parameters

- lib/open_api_spex/cast.ex
- lib/open_api_spex/cast/object.ex
- test/cast/object_test.exs
- test/operation2_test.exs
- test/plug/cast_and_validate/custom_error_user_controller_test.exs
- test/plug/cast_and_validate_test.exs
OpenApiSpex was not adhering to the OpenAPI spec for object schemas that have `additionalProperties` set to `true`. OpenApiSpex treated the input value as valid for that case, but it didn't pass the object's properties through.
It now passes unrecognized properties though, but it does not convert string property keys to atoms, because that would require a call to `String.to_atom/1` which is not safe in this context.
> Allow additional properties to pass through in cast

- README.md
- lib/open_api_spex.ex
- lib/open_api_spex/open_api.ex
- lib/open_api_spex/open_api/decode.ex
- test/open_api/decode_test.exs
- test/support/encoded_schema.json
**Reference issues**
- https://github.com/open-api-spex/open_api_spex/issues/51
**Summary**
Add ability to convert a Map into an OpenApi struct.
**Motivation**
We are adding this to enable users that may already have Open API schemas encoded in common formats such as YAML or JSON, or users that don't want to commit to the macro-based approach provided, to benefit from the library's validation capabilities.
**Design**
> *NOTE*: It's worth calling out that we're not doing any parsing of the schema files, we're deferring that responsibility to the users, we think that this reduces complexity of the library while allowing the users to use any file formats or parsers they wish.
The bulk of the new functionality lives in OpenApiSpex.OpenApi.Map.decode/1 which takes a map() and returns an …
> Add open api spex map decode

- lib/open_api_spex.ex
- test/support/schemas.ex
Before this would raise `** (Protocol.UndefinedError) protocol
Enumerable not implemented for %OpenApiSpex.Schema{}` because at this
point the function was recursively called with a struct instead of a map
like the first time.
> Allow property of compiled schema to be a schema

- lib/open_api_spex/cast/all_of.ex
- lib/open_api_spex/cast/discriminator.ex
- lib/open_api_spex/cast/one_of.ex
- lib/open_api_spex/plug/json_render_error.ex
- lib/open_api_spex/schema.ex
- test/cast/all_of_test.exs
- test/cast/discriminator_test.exs
- test/plug/cast_test.exs
- test/schema_test.exs
- test/support/api_spec.ex
- test/support/pet_controller.ex
- test/support/router.ex
- test/support/schemas.ex
- Fixes `anyOf`/`oneOf`/`allOf` definitions for `Pet`, extracts discriminating field from `Pet` to `PetType`, but keeps the discrimination definition on `Pet`. `Cats` and `Dogs` will now extend the `PetType` definition instead of `Pet` = remove circular reference.
- If `x-struct` is set in `allOf` schema, the values will now be casted to the given struct.
- Forward `Schema.cast/3` for `oneOf`/`allOf` Schemas to `Cast.cast()` (#160) 
- Fixes issue with `json_render` when a error occurs on root-level (`path: []`)
- Implements `PhoenixController` for pets for the purpose of testing the `oneOf/allOf` Struct-Casting thing
Please let me know if you'r not happy with some of the changes :smile:
> Fixes issues with complex types for phoenix endpoints

- lib/open_api_spex/cast/one_of.ex
- test/cast/one_of_test.exs
- test/support/one_of_schemas.ex
- test/support/open_api.ex
- test/support/pet_controller.ex
Fixes `oneOf` casting where the input value is compared against the properties of the `oneOf` schemas.
Fixes #165.
> Fix oneOf for object schemas

- lib/open_api_spex/controller.ex
- test/controller_test.exs
- test/support/user_controller_annotated.ex
Changes the name of the key that the requestBody is defined under. It was `body`, but it's now `requestBody` to be consistent with the Open API name.
Also updates the docs and tests to document and test the `requestBody`.
> Change key name for requestBody in ExDoc operation

- lib/open_api_spex/cast_parameters.ex
- test/cast_parameters_test.exs
- test/operation2_test.exs
Related to [#168](https://github.com/open-api-spex/open_api_spex/issues/168)
> Fix casting for unsupported params

- README.md
This adds example code how to use `Application.spec/2` in `%Info` struct.
See #173 for more.
> Update README for Info from Application.spec/2

- lib/open_api_spex/cast.ex
- lib/open_api_spex/cast/error.ex
- lib/open_api_spex/cast/number.ex
- test/cast/number_test.exs
- Added `OpenApiSpex.Cast.Number` (patterned after `OpenApiSpex.Cast.Integer`),
- Added corresponding `number_test.exs`
- Fixed the `Error` type spec to allow `float()` as well as `integer()` for `:minimum`/`:maximum`
> Fix for #181 that adds minimum/maximum validation for number properties

- lib/open_api_spex/cast_parameters.ex
- test/plug/cast_test.exs
- test/support/pet_controller.ex
- test/support/router.ex
There is currently a issue with the validation of header parameters.
The Issue is, that when you specify a custom header parameter, for example a required `x-user-id` parameter. This will result in a error since the validator is looking for this parameters but can't finde it because currently only the path and query params will be passed to cast&validate part. 
With this PR this issue will be fixes plus the validation respects the "location" of the parameter. This means, if you pass the `x-user-id` as query parameter this will also return in a error. 
I'm not quite happy with the look of the code, so if someone finds something to improve I'm more than happy to do so
> Separates request param validation based on their scope

- lib/open_api_spex/cast_parameters.ex
- test/plug/cast_test.exs
- test/support/pet_controller.ex
- test/support/router.ex
- test/support/utility_controller.ex
This PR is based on #184 since it makes the injection of the property based ap field much easier
Closes #171 
Note: Only `additionalProperties: true` is supported at the moment
> Support free-form query parameters

- lib/open_api_spex/inspect/for_schema.ex
- test/inspect/for_schema_test.exs
When inspecting `%Schema{}`, it produces a large amount of output that is difficult to parse. It gets worse when working with schema from actual codebases that use OpenApiSpex.
This PR makes the output of Elixir's `inspect()` call more compact when inspecting `%Schema{}`.
Running `IO.inspect(%OpenApiSpex.Schema{title: "Hello"})`, before and after:
Before:
```
%OpenApiSpex.Schema{discriminator: nil, uniqueItems: nil, additionalProperties: nil, minLength: nil, maxProperties: nil, deprecated: nil, required: nil, pattern: nil, minItems: nil, oneOf: nil, readOnly: nil, writeOnly: nil, description: nil, exclusiveMaximum: nil, format: nil, nullable: nil, maxLength: nil, title: "Hello", allOf: nil, type: nil, anyOf: nil, enum: nil, "x-struct": nil, xml: nil, exclusiveMinimum: nil, maximum: nil, …
```
> Better inspect

- lib/open_api_spex.ex
- test/schema_test.exs
It's easy to forget to set the `:title` property when defining schemas that become named components. When a component's title left as `nil`, it causes strange behavior that is difficult to debug. The strange behavior happens when OpenApiSpex's is unable to resolve references. Component references are based on the schema's title, and when the title is `nil`, OpenApiSpex can't reliably find the component.
It seems like the library would be easier to use if the `:title` property wasn't required. If the title is auto-generated in a uniform way, it will make make components consistently reflect the Elixir module that defines them.
> Auto-populate schema title from module name

- lib/open_api_spex/controller.ex
- test/controller_test.exs
- test/support/user_controller_annotated.ex
Allow operation_id to be specified if desired.
> derive operation id from meta as well

- lib/open_api_spex/open_api/decode.ex
I don't think a `properties` key needs to be present in an OpenSchema object schema, does it?
> Make 'properties' key option when parsing doc

- lib/open_api_spex/controller.ex
- test/controller_test.exs
- test/support/schemas.ex
- test/support/user_controller_annotated.ex
Currently using doc-based specs, endpoint responses can be specified using a 3-element tuple:
```
@doc responses: [
ok: {"User response", "application/json", User}
]
```
This works fine when the response is inlined in the controller. However, to support shared responses that are defined outside the controller, it makes sense to support the longer-form format that uses the `%Response{}` struct.
```
@doc responses: [
ok: {"User response", "application/json", User},
not_found: NotFound.response()
]
```
...where `NotFound.response()` is:
```
def response do
Operation.response("Not Found", "application/json", NotFound)
end
```
> Allow `%Response{}` struct in doc-based spec

- lib/open_api_spex/plug/swagger_ui.ex
This is the latest version available on the CDN.
Fixes #209.
> Upgrade Swagger UI to 3.24.2

- lib/open_api_spex/controller.ex
- lib/open_api_spex/operation.ex
- lib/open_api_spex/schema.ex
- test/cast_parameters_test.exs
- test/support/pet_controller.ex
- test/support/user_controller.ex
This PR adds some validation to `Operation.parameter/5`, helping to avoid a couple of mis-uses of this function, including
- Omitting the description, causing the keyword opts to be placed in the description parameter
- Passing invalid options in the opts, eg `default:` which should be in the `Schema`, not the `Parameter`
The code now has a guards for the types of all parameters, uses `struct!` to validate
opts, and has better documentation for the parameters types.
I've fixed the test support code where it was being misused.
> Validate Operation.parameter/5 args

- README.md
Increments the readme with some usage examples for specifying `SecurityScheme` and declare it as part of `security`.
> Add SecurityScheme usage and examples in the readme

- lib/open_api_spex/schema.ex
Schemas using explicit References would fail to compile.
With this change they will work with with the limitation that the `default` value declared in the referenced schema is not declared in the struct associated with the schema.
The use case for an explicit reference over a module is to enable recursive schemas.
> Handle explicit %Reference{} in schemas during compilation

- lib/open_api_spex/plug/cast_and_validate.ex
If there was no content type header in the request, it was
transformed to "", making it fall through a check that
no body was present if the body is optional , resulting
in "Invalid value for header: content-type" errors.
> CastAndValidate: Fix incorrect content-type handling

- lib/open_api_spex/controller.ex
- test/support/user_controller_annotated.ex
More informative exception when docs are missing for controller action
Before:
```
** (MatchError) no match of right hand side value: nil
```
After:
```
[warn] No docs found for function Elixir.SppWeb.Api.MessageController.indexb/2
```
Allow response spec to have 4th "opts" argument
The shape of a response in the `@doc responses:` keyword-list/map was:
```elixir
{http_status, {description, mime_type, schema}}
```
A fourth element of the inner tuple was previously accepted (maybe it ignored?), but a recent
revision of OpenApiSpex made it a raised exception:
```
** (FunctionClauseError) no function clause matching in anonymous fn/1 in OpenApiSpex.Controller.build_responses/1
```
This commit change passes an optional fourth element to the `opts` argument of `Operation.response/4`.
> Doc based specs fixes

- lib/open_api_spex/cast/one_of.ex
- test/cast/one_of_test.exs
- test/support/one_of_schemas.ex
Accompanying PR for #226 
As described by https://github.com/swagger-api/swagger.io/issues/253 i added some required fields and because of that was able to remove the forced `additionalProperties: false`.
I guess forcing this to false was only needed because the example was wrong...
Obviously if people expect this behaviour, then it might break their current implementation. But probably because their sub schemas lack the required fields...
I don't fully understand why `anyOf: nil` was being set, but all tests were happy without it. If there is a valid reason to keep it, maybe a test should be added (happy to do that if needed) ?
> Improve oneOf casting

- README.md
- examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller.ex
- examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller_with_struct_specs.ex
- lib/open_api_spex/controller.ex
- test/operation_test.exs
- test/path_item_test.exs
- test/support/cast_and_validate/custom_error_user_controller.ex
- test/support/custom_error_user_controller.ex
- test/support/pet_controller.ex
- test/support/user_controller.ex
- test/support/utility_controller.ex
Converts to using ExDoc-based operation specs. All struct-based specs have been converted throughout the codebase, except for examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller_with_struct_specs.ex.
The README now uses ExDoc-based operation spec examples exclusively.
Also adds two small spec parsing improvements to `OpenApiSpex.Controller` to reduce sharp edges a bit.
> Promote ExDoc-based operation specs

- examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller.ex
- lib/open_api_spex/controller.ex
- test/controller_test.exs
- test/support/user_controller_annotated.ex
Gracefully handle cases where a user omits the `@doc` string for an operation.
> Handle missing description

- README.md
- lib/open_api_spex/controller.ex
- test/controller_test.exs
- test/support/user_controller_annotated.ex
Raised by https://github.com/open-api-spex/open_api_spex/issues/234
Allow to pass `false` to `@doc` annotation to skip the warning.
Actions without doc get warn as it was to notify the user about missing documentation.
Made a change to `readme.md` file for new setting
> Handle doc false

- README.md
- lib/open_api_spex/controller.ex
- test/controller_test.exs
- test/support/user_controller_annotated.ex
Raised by https://github.com/open-api-spex/open_api_spex/issues/235
`parameters:` now support `:schema` key
Added exclusive `ArgumentError` check if both are specified
Updated the `readme.md` example with explicit `Schema` in parameters and shortcut usage
> Make @doc parameters declaration consistent with open api

- lib/open_api_spex/controller.ex
- test/controller_test.exs
- test/support/user_controller_annotated.ex
Found a bug after PR in https://github.com/open-api-spex/open_api_spex/issues/235 with default type value at
```
{type, options} = Keyword.pop(options, :type, :string)
```
The exclusive constraint triggers in this case if I specified only `:schema`. 
Added few more tests to cover the case
Thanks
Hope nothing got damaged :)
> Remove default pop value for :type shortcut

- lib/open_api_spex/open_api/decode.ex
This addition fixes nested structures (namely arrays of other object schemas) when using a file as the schema source, instead of reading directly from the documentation.
> Fix for nested parameters when served from file based schema

- lib/open_api_spex/cast/error.ex
- lib/open_api_spex/cast/one_of.ex
- test/cast/one_of_test.exs
- test/plug/cast_test.exs
Fixes #244 
* Fixes incorrect string error message
* Cleans up string error message to summarize why the oneOf failed.
* Tracks failures to validate against child schemas, and separates tracking from successful validation against child schemas.
> #244 Fix error handling for oneOf

- CHANGELOG.md
- README.md
- ROADMAP.md
- examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller.ex
- examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller_with_struct_specs.ex
- examples/plug_app/lib/plug_app/user_handler.ex
- lib/open_api_spex/json_error_response.ex
- lib/open_api_spex/plug/cast_and_validate.ex
- lib/open_api_spex/plug/default_render_error.ex
- lib/open_api_spex/plug/json_render_error.ex
- lib/open_api_spex/plug/json_render_error_v2.ex
- test/plug/cast_test.exs
- test/plug/json_render_error_test.exs
- test/support/controllers/json_render_error_controller.ex
- test/support/pet_controller.ex
- test/support/router.ex
- test/support/schemas.ex
- test/support/user_controller.ex
- test/support/utility_controller.ex
Deprecate the `message` field. It was originally added by mistake. The original intent was to make the error shape compatible with json:api. Adds `detail` in its place.
Also adds documentation explaining that a module-based schema doesn't need a `:title`. Leaving the title off and letting OpenApiSpex generate it makes the code more resilient to renaming changes, and fewer difficult debugging sessions.
> Introduce new `detail` field in the response JSON of `JsonRenderError`

- README.md
This PR fixes #247.
The current responses example has a typo in what should be `unprocessable_entity` (currently _unprocessible_) according to the documentation of `Plug.Conn.Status`, making it to not compile when trying to directly follow the example.
Example of the issue:
```elixir
@doc responses: [
ok: {"User", "application/json", MyAppWeb.Schema.User}
unprocessible_entity: {"Bad request parameters", "application/json", MyAppWeb.Schema.BadRequestParameters},
not_found: {"Not found", "application/json", MyAppWeb.Schema.NotFound}
]
```
> Fixes README.md responses example typo "unprocessible"

- README.md
`securitySchemes` wants binary for the keys: https://github.com/open-api-spex/open_api_spex/blob/dca4b885bbce81269d038eaf4b5cb9a290b25804/lib/open_api_spex/components.ex#L47
> fix security example to use correct types for the keys

- lib/open_api_spex/controller.ex
- test/controller_test.exs
- test/support/user_controller_annotated.ex
This change adds support for the `security` attribute on docstring metadata, it works for my simple test case of just specifying `security: [%{"authorization" => []}]` on some operations.
fixes #250
> Support `security` doc string attribute on operations

- lib/open_api_spex/open_api/decode.ex
- lib/open_api_spex/operation2.ex
- lib/open_api_spex/reference.ex
- test/open_api/decode_test.exs
- test/operation2_test.exs
- test/support/encoded_schema.json
The Open API Specification states the [Operation Object](https://swagger.io/specification/#operationObject) allows the `requestBody` field to be defined as either a [Request Body Object](https://swagger.io/specification/#request-body-object) or a [Reference Object](https://swagger.io/specification/#reference-object). The typespec for the `OpenApiSpex.Operation` module also matches the spec and is defined as `RequestBody.t() | Reference.t() | nil`.
This pull request adds support for using a reference as an Operation's request body.
Fixes #259.
> Allow a reference to be used for an Operation's request body

- examples/phoenix_app/lib/phoenix_app/accounts/accounts.ex
- examples/phoenix_app/lib/phoenix_app/accounts/user.ex
- examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller.ex
- examples/phoenix_app/lib/phoenix_app_web/router.ex
- lib/open_api_spex/paths.ex
- test/paths_test.exs
- test/support/pet_controller.ex
- test/support/router.ex
Fixes #123 
When two (or more) routes map to the same operation, the first is left unchanged,
while the rest will have an index in parens appended to the `operationId`.
Example:
> Handle the same operation occurring at different routes

- examples/phoenix_app/lib/phoenix_app_web/endpoint.ex
- examples/phoenix_app/lib/phoenix_app_web/router.ex
- lib/open_api_spex/plug/swagger_ui.ex
This PR forwards plug opts from the `SwaggerUI` plug to the `SwaggerUIBundle` constructor.
Usage example:
```elixir
get "/swaggerui", OpenApiSpex.Plug.SwaggerUI,
path: "/api/openapi",
default_model_expand_depth: 3,
display_operation_id: true
```
> Allow SwaggerUI to be configured via Plug opts

- lib/open_api_spex/cast_parameters.ex
- test/cast_parameters_test.exs
HTTP headers are case-insensitive according to:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
This commit updates the OpenApiSpex.CastParameters module to ignore
casing when casting header parameters.
This will allow users to declare header parameters using their upper
case form, like "Content-Type", and still get the parameter casted when
its provided in its downcase form.
> Updates header casting logic to be case-insensitive

- lib/open_api_spex/open_api.ex
- lib/open_api_spex/plug/cache.ex
- lib/open_api_spex/plug/cast.ex
- lib/open_api_spex/plug/cast_and_validate.ex
- lib/open_api_spex/plug/put_api_spec.ex
- lib/open_api_spex/plug/render_spec.ex
- test/plug/render_spec_test.exs
When a request fails to pattern match on a controller action, the resulting error report can be overwhelmingly large. In a recent test, the error report was 83k characters.
There doesn't seem to be a good reason to pass the Open API spec and the Operations lookup into the Conn. That data is already in the in-memory cache.
By removing the data from the Conn, the same error report is only 2k characters in size. It becomes much easier to figure out the bad pattern match.
> Remove unnecessary data passing in conn

- lib/open_api_spex/open_api/decode.ex
Making sure format remains as an atom so that parameter casting does not fail pattern matching when casting and validating
> AddFormatToSpecialTratmentValuesWhenDecodingOpenApi

- lib/open_api_spex/controller_specs.ex
- test/controller_specs_test.exs
- test/support/dsl_controller.ex
Hi there!
Thanks for the library, the thing is that we wanted to add the `deprecated` flag to the operation used @doc based API and it collisions with Elixir deprecated flag, later we found the new `operation` API and it misses the flag so we just added it.
Do I need to do anything else for this to be accepted?
Thanks in advance
> ControllerSpecs add support for deprecated

- lib/open_api_spex/info.ex
The value could be other map or list the same way as in
`OpenApiSpex.OpenApi`.
> Fix type of extensions in OpenApiSpex.Info

- lib/open_api_spex.ex
Closes #303 .
This change enables specifying an `x-struct` value in the `%Schema{}` struct when using the `OpenApiSpex.schema/1` macro.
Previously, the value for this field would be overridden with the module where the schema is defined.
Now, the logic will check to see if an `x-struct` value is specified. If not, it will fall back to the prior logic.
@mbuhot let me know if this is satisfactory as per our discussion on #303 . Thanks!
> Allow specifying x-struct directive when using the schema/1 macro

- mix.exs
> Fix .formatter.exs doens't include in published package

- lib/open_api_spex/controller.ex
- test/controller_test.exs
When documenting an operation from the @doc tag, use the first line as
summary and the rest of it as description, without repeating the summary
in the description.
This changes current behaviour, but I feel it's better to not repeat the
summary in the description, which usually appears shortly after.
Feedback is welcome :)
> Do not repeat the summary in the description

- README.md
- lib/open_api_spex/controller.ex
- lib/open_api_spex/controller_specs.ex
- test/open_api/decode_test.exs
Because of #242, ExDoc-based operation specs is not a reliable API across different versions of Elixir. `ControllerSpecs`, introduced in version 3.9, offers a similar lightweight syntax as the ExDoc API without the same limitation. This PR updates the README to promote `ControllerSpecs` as the preferred API for defining operations specs.
> Promote ControlerSpecs as the preferred API for controller operations

- lib/open_api_spex.ex
- lib/open_api_spex/schema_resolver.ex
- test/schema_resolver_test.exs
Sometimes it is desired to define a schema that isn't referenced by a Plug or Controller. For example, a Phoenix Channel communicates in JSON, and that JSON can be specified with OpenApiSpex. This PR adds a function `OpenApiSpex.add_schemas/2` that resolves the given functions and adds them to the `OpenApi` struct as component schemas.
> Function for adding additional schemas to an OpenApi spec struct

- CHANGELOG.md
- README.md
- mix.exs
Thanks to the contributions of the community ❤️💙💛💜🧡
- [noozo](https://github.com/noozo)
- [sernajoto](https://github.com/sernajoto)
- [pacoguzman](https://github.com/pacoguzman)
- [vitorleal](https://github.com/vitorleal)
- [zlarsen](https://github.com/zlarsen)
- [surik](https://github.com/surik)
- [brentjr](https://github.com/brentjr)
- [dwmcc](https://github.com/dwmcc)
- [wingyplus](https://github.com/wingyplus)
- Feature: Support OAuth2 for swagger-ui (#217)
- Feature: Support `default` response type in responses (#301)
- Feature: Allow overriding `x-struct` in `OpenApiSpex.shcmea/1` (#304)
- Feature: Ability to specify `deprecated` in ControllerSpec operation (#296)
- Feature: `:struct?` and `:derive?` options in `OpenApiSpex.schema/1` (#312)
- Feature: `OpenApiSpex.add_schemas/2` …
> Version 3.10.0

- lib/open_api_spex/plug/swagger_ui.ex
Dont encode functions for swagger UI, now you are able to set authentication by initiating the SwaggerUi plug like so:
```elixir
get "/", OpenApiSpex.Plug.SwaggerUI,
path: "/v1/openapi",
onComplete: "function(){ ui.preauthorizeApiKey(\"brand\", \"ad\"); }"
```
solution for: https://github.com/open-api-spex/open_api_spex/issues/324
> feat(ui): dont json encode swagger-ui methods

- lib/open_api_spex/controller_specs.ex
- lib/open_api_spex/operation.ex
- test/controller_specs_test.exs
- test/operation_test.exs
- test/support/dsl_controller.ex
This commit adds the `:headers` to the list of opts that `Operation.response` can receive.
Additionally, it describes how for the `operation` macro these optional values can assigned to the inside the `responses:` key.
Fixes #331
> Add optional header in `opts` to Operation.response

- README.md
- `title` is required, fails to generate spec without it
- Missing comma after first value
- Need to call `to_string` on the values from Application.spec or they won't be generated as you expect
> Fix Application.spec/2 example in README

- lib/open_api_spex/cast.ex
- lib/open_api_spex/cast/error.ex
- lib/open_api_spex/cast/object.ex
- lib/open_api_spex/test/test_assertions.ex
- test/cast/object_test.exs
- test/plug/cast_test.exs
- test/schema_test.exs
- test/support/api_spec.ex
- test/support/schemas.ex
- test/support/user_controller.ex
- test/test_assertions_test.exs
This PR adds the helpers `assert_request_schema` and `assert_response_schema` to OpenApiSpex.TestAssertions. They can be useful to validate request and response schemas, respectively, when there are required `writeOnly` or `readOnly` properties being used. Fixes #335 
Relevant changes
- Creates new helpers `assert_request_schema` and `assert_response_schema`
- The original `assert_schema` helper has a new optional argument `assert_operation`, to indicate the operation being validated. If it's not provided (or is `nil`), it fallbacks to the current behavior.
- Adds a property `password` to the example `User` schema, to serve as an example (and test case) for a `writeOnly` required field
> Adding helpers to OpenApiSpex.TestAssertions

- lib/open_api_spex/cast/object.ex
- test/cast/object_test.exs
Trying to fix the issue with minimal changes.
Technically, `cast_property` could be simplified and execute only cast operation without output map update and output map update moved to `cast_properties`.
> Collect all errors occurred during cast properties (#351)

- lib/open_api_spex/controller.ex
- lib/open_api_spex/controller_specs.ex
- lib/open_api_spex/operation_builder.ex
- test/controller_specs_test.exs
- test/controller_test.exs
- test/support/dsl_controller.ex
- test/support/user_controller_annotated.ex
Fixes #328
This allows you to do either:
```elixir
defmodule MyApp.SomeController do
@moduledoc external_docs %{
description: "My description",
url: "http://example.com/"
}
...
end
```
or:
```elixir
defmodule MyApp.SomeController do
@doc external_docs %{
description: "My description",
url: "http://example.com/"
}
def create, do: ...
...
end
```
or:
```elixir
defmodule MyApp.SomeController do
use OpenApiSpex.ControllerSpecs
operation :create,
external_docs %{
description: "My description",
url: "http://example.com/"
}
def create, do: ...
...
end
```
... and the map referenced by `external_docs` will end up as the `externalDocs` property of the relevant operation(s) - if used from the `@moduledoc`, it will be added to all operations.
This is a draft PR to motivate the conversation in #328.
> external_docs via controller @doc and @moduledoc or ControllerSpecs DSL

- lib/open_api_spex/schema.ex
- test/schema_test.exs
Hi there,
I think that I found a bug. When we are working with schema modules and try to generate an example with `Schema.example` it returns `nil`. As an example, given the schema module below:
```elixir
defmodule Bar do
require OpenApiSpex
OpenApiSpex.schema(%{
type: :object,
properties: %{
baz: %Schema{
type: :int,
example: 2
}
}
})
end
defmodule Foo do
require OpenApiSpex
OpenApiSpex.schema(%{
type: :object,
properties: %{
bar: Bar,
foo: %Schema{
type: :string,
example: "1"
}
}
})
end
```
When we try to generate the example we get:
```elixir
> Schema.example(Foo)
> nil
```
but we should expect to get `%{bar: %{baz: 2}, foo: "1"}`.
So, I made a quick fix and put one test :)
Thanks!
> fix: Schema.example/1 for schema module

- lib/open_api_spex/cast/one_of.ex
- test/cast/one_of_test.exs
> Handle oneOf cast when there are multiple success along with failure

- lib/open_api_spex/cast/any_of.ex
- test/cast/any_of_test.exs
`anyOf` casting is validating just against the first schema.
Accordingly the json schema definition: 
> To validate against anyOf, the given data must be valid against any (one or more) of the given subschemas.
The following code returns an error:
```elixir
test "should cast multiple schemas" do
dog_schema = %Schema{
title: "Dog",
type: :object,
properties: %{
breed: %Schema{type: :string},
age: %Schema{type: :integer}
}
}
food_schema = %Schema{
title: "Food",
type: :object,
properties: %{
food: %Schema{type: :string},
amount: %Schema{type: :integer}
}
}
schema = %Schema{anyOf: [dog_schema, food_schema], title: "MyCoolSchema"}
value = %{"breed" => "Corgi", "age" => 3, "food" => "meat"}
assert {:ok, %{breed: "Corgi", age: 3, food: "meat"}} = cast(value: value, schema: schema)
end
```
This …
> fix: any_of cast for multiple schemas

- lib/open_api_spex/paths.ex
In phoenix you can define the endpoint `host` as nil and then use host prefixes to define host specific routes in the router. 
```
scope "/", TestappWeb, host: "api." do
pipe_through :browser
get "/", PageController, :index
end
```
This is helpful if you want for instance serve different sets of apis and describe them with separate specs from the same phoenix instance:
```
paths: Paths.from_router(router, host: "api.")
```
This simply adds the ability to filter phoenix routes when calling `Paths.from_router`, so that one can easily generate a spec only for routes having a specific attribute value. This covers not only the `host` use case, but filtering on any phoenix route attribute.
> Add support for multiple specs for the same Phoenix router

- lib/open_api_spex/plug/swagger_ui.ex
This PR updates swagger, so a token or similar can be persisted during page refresh.
fixes: [375](https://github.com/open-api-spex/open_api_spex/issues/375)
```elixir
get("/swaggerui",
to: OpenApiSpex.Plug.SwaggerUI,
init_opts: [
path: "/api/openapi",
apisSorter: "alpha",
operationsSorter: "alpha",
tagsSorter: "alpha",
persistAuthorization: true # the good stuff :)
]
)
```
> chore: updated swagger to 3.34.0

- lib/open_api_spex/json_error_response.ex
- test/plug/cast_test.exs
- test/support/user_controller.ex
Fixes: #384
The `OpenApiSpex.JsonErrorResponse` schema did not
contain a type for its error items, this caused
generated responses from `OpenApiSpex.Plug.CastAndValidate`
to not match JsonErrorResponse with errors like:
```
Value does not conform to schema JsonErrorResponse: Invalid schema.type. Got: nil at /errors/0
%{"errors" => [%{"detail" => "Invalid value for enum", "source" => %{"pointer" => "/type"}, "title" => "Invalid value"}]}
```
> Fix JsonErrorResponse schema definition

- lib/open_api_spex/json_error_response.ex
Fixed naming mismatch in comments of the `json_error_response.ex` file.
> JsonApiErrorResponse vs JsonErrorResponse

- lib/open_api_spex/controller.ex
I think the intention was to interpolate the inspected controller name but the code block shows the original source which makes it, IMO, unnecessarily confusing as an example, since if you copy this code it fails to compile, but if you omit that line it silently fails to load the docs, which was frustrating as a beginner.
> Clarify controller example

- lib/open_api_spex/open_api/decode.ex
fixes an issue found when parsing Encodings without the `style` field
example:
```
"post": {
"operationId": "TransferMtData",
"requestBody": {
"content": {
"multipart/related": {
"encoding": {
"binaryMtData": {
"contentType": "application/vnd.3gpp.5gnas",
"headers": {
"Content-Id": {
"schema": {
"type": "string"
}
}
```
produces the following error:
```
** (FunctionClauseError) no function clause matching in String.to_atom/1    
The following arguments were given to String.to_atom/1:
nil
Attempted function clauses (showing 1 out of 1):
def to_atom(+string+) when -is_binary(string)-
(elixir 1.13.0-dev) lib/string.ex:2436: String.to_atom/1
(open_api_spex 3.11.0) lib/open_api_spex/open_api/decode.ex:94: OpenApiSpex.OpenApi.Decode.update_map_if_key_present/3
(open_api_spex 3.11.0) …
```
> Fix casting Encoding without style field

- lib/open_api_spex/open_api/decode.ex
- test/open_api/decode_test.exs
- test/support/encoded_schema.json
Before this PR `OpenApiSpex.OpenApi.Decode.decode/1` function did not take into account extensions in creating the `%OpenApi{}` struct. Now extensions are correctly parsed and the corresponding field is populated in all structs that support it.
> decode/1 function correctly populates the :extensions field of structs

- lib/open_api_spex/cast.ex
- test/cast_test.exs
> [change] allow empty schemas to be validated as wildcards

- lib/open_api_spex/schema.ex
Fixes the minor syntax issues with the example of a schema that were preventing it from compiling (#431).
> Fix schema example minor syntax issues (#431)

- lib/mix/tasks/openapi.spec.json.ex
- lib/open_api_spex/open_api.ex
See: https://github.com/open-api-spex/open_api_spex/issues/436
The `--vendor-extensions=boolean` flag when set to:
* true   : Keeps vendor extensions in the generated openapi.json file
* false  : Strips vendor extensions in the generated openapi.json file
The current vendor extensions are x-struct and x-validate.
> Implement flag to omit vendor extensions in mix openapi.spec.json

- lib/open_api_spex/cast/string.ex
- lib/open_api_spex/schema.ex
- test/cast/string_test.exs
- test/schema_test.exs
This is a continuation of https://github.com/open-api-spex/open_api_spex/pull/266#discussion_r475041706
we should generate valid examples for as many formats as possible.
The current behaviour regarding UUIDs is illustrated in the following example:
```elixir
defmodule SomeSchema do
require OpenApiSpex
alias OpenApiSpex.{Schema, Cast}
OpenApiSpex.schema(%{
description: "some schema",
type: :object,
properties: %{
id: %Schema{
type: :string,
format: :uuid
}
}
})
end
OpenApiSpex.Cast.cast(SomeSchema.schema, OpenApiSpex.Schema.example(SomeSchema))
```
The generated `example` contains an invalid UUID and `cast/2` doesn't validate it at all returning a success tuple.
> Generate examples for UUID formatted strings

- lib/open_api_spex/json_error_response.ex
Like #248 fixed the same typo in the README, this PR fixes it in the result of the function mentioned in the title (which shows up in the responses section of Swagger UI when calling it as shown in the example in the `@doc` above).
> Fix typo in result of JsonErrorResponse.response()

- lib/open_api_spex.ex
- lib/open_api_spex/cast_parameters.ex
- lib/open_api_spex/operation2.ex
- lib/open_api_spex/plug/cast_and_validate.ex
- test/operation2_test.exs
- test/plug/cast_test.exs
- test/support/router.ex
- test/support/user_no_replace_controller.ex
See #398 and #376
As aked in [this comment](https://github.com/open-api-spex/open_api_spex/pull/376#issuecomment-1009472277) the flag for moving cast result to `conn.private` is now an option to `CastAndValidate` plug.
Credits to @riccardomanfrin and @lucacorti
> Avoids overwriting Plug.Conn body_params and params with the cast outcome

- README.md
- lib/open_api_spex/controller_specs.ex
- lib/open_api_spex/operation.ex
- lib/open_api_spex/operation_builder.ex
- test/controller_specs_test.exs
- test/support/dsl_controller.ex
Adds support for multiple content types for request bodies and response bodies in the ControllerSpecs DSL.
Resolves #450.
> Multiple content types

- lib/open_api_spex/operation.ex
#451 introduced a change that doesn't meet OpenAPI specification. https://spec.openapis.org/oas/v3.1.0#fixed-fields-14 - content can be empty. 
The mentioned change caused errors in following example
```
operation(:operation,
summary: "summary",
description: "description",
request_body: {nil, "application/json", SchemaRequest},
responses: %{
201 => {"Operation succeed", nil, nil}
}
)
```
```
** (RuntimeError) Expected string or map for request_body: nil
(open_api_spex 3.11.0) lib/open_api_spex/operation.ex:320: OpenApiSpex.Operation.build_content_map/2
(open_api_spex 3.11.0) lib/open_api_spex/operation.ex:161: OpenApiSpex.Operation.response/4
(open_api_spex 3.11.0) lib/open_api_spex/operation_builder.ex:82: anonymous fn/1 in OpenApiSpex.OperationBuilder.build_responses/1
(elixir 1.13.1) …
```
> fix: allow empty content for Response

- lib/open_api_spex/operation_builder.ex
- test/controller_specs_test.exs
- test/support/dsl_controller_operation_structs.ex
The operation macro currently supports passing arguments for url params, request body and response schemas in a "simplified" way (as tuples/keyword lists).
It also supports passing operation structs like `%Parameter{}` and `%Response{}`.
However, it didn't support passing `%RequestBody{}`, for example this:
```elixir
operation :update
summary: "Update user",
request_body: %RequestBody{
#...
}
```
would result in `%Operation{requestBody: nil}`.
This changeset fixes it so that we get the expected behaviour of
`%Operation{requestBody: %RequestBody{}}`.
Fixes: https://github.com/open-api-spex/open_api_spex/issues/457
> fix: support RequestBody passed to operation macro

- lib/open_api_spex/components.ex
- lib/open_api_spex/contact.ex
- lib/open_api_spex/discriminator.ex
- lib/open_api_spex/encoding.ex
- lib/open_api_spex/example.ex
- lib/open_api_spex/extendable.ex
- lib/open_api_spex/external_documentation.ex
- lib/open_api_spex/header.ex
- lib/open_api_spex/license.ex
- lib/open_api_spex/link.ex
- lib/open_api_spex/media_type.ex
- lib/open_api_spex/oauth_flow.ex
- lib/open_api_spex/oauth_flows.ex
- lib/open_api_spex/open_api/decode.ex
- lib/open_api_spex/request_body.ex
- lib/open_api_spex/schema.ex
- lib/open_api_spex/server.ex
- lib/open_api_spex/server_variable.ex
- lib/open_api_spex/xml.ex
- test/open_api/decode_test.exs
- test/support/encoded_schema.json
[Swagger documentation](https://swagger.io/docs/specification/openapi-extensions/) that was used in PR #415  is outdated.
By reading [OpenApi sepcification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md) one can see that almost all objects can be extended with custom extensions. This PR adds the Extendable implementation to all the missing structures a part for `Paths`, `Responses`, and `Callback` that are not defined as structs thus making it difficult to add extensions.
> Allow extensions in all OpenApi structures

- lib/open_api_spex/cast/integer.ex
- test/cast/integer_test.exs
Validate min/max for both `:int32` and `:int64` format. It'll returns
`:invalid_format` when the value is outside of their range.
Fixes #402
> Validate :integer type format

- lib/open_api_spex/cast/integer.ex
- test/cast/integer_test.exs
Treat float number as invalid type when set type to `:integer`.
Fixes #467
> Do not accepting float number in integer type

- lib/open_api_spex/cast/any_of.ex
- test/cast/any_of_test.exs
> Fix anyOf cast crash when Cast.cast return a struct

- lib/open_api_spex/open_api/decode.ex
- test/open_api/decode_test.exs
- test/support/encoded_schema.json
This simply change the order of evalutaion during decode phase checking first if a discriminator is present and then decoding it as an object.
Without this fix the new test would have returned:
```elixir
%OpenApiSpex.Schema%{
discriminator: %{
"propertyName" => "userType"
},
oneOf: [
%{"$ref" => "#/components/schemas/User"},
%{"$ref" => "#/components/schemas/SpecialUser"}
],
properties: %{},
type: :object
}
```
instead of 
```elixir
%OpenApiSpex.Schema%{
discriminator: %OpenApiSpex.Discriminator{
extensions: nil,
mapping: nil,
propertyName: "userType"
},
oneOf: [
%OpenApiSpex.Reference{"$ref": "#/components/schemas/User"},
%OpenApiSpex.Reference{"$ref": "#/components/schemas/SpecialUser"}
],
type: "object"
}
```
> fix decoding of discriminators when `type: object` is present

- lib/open_api_spex/operation2.ex
- test/operation2_test.exs
At the moment the casted value of not map bodies is simply discarded
> Correctly cast not map bodies (plug puts them under _json key)

- lib/open_api_spex/plug/put_api_spec.ex
Now allows configuration of spec cache instead of compiling the default cache at compile time.
fixes https://github.com/open-api-spex/open_api_spex/issues/443
I'm currently replacing the PutApiSpec and RenderView in the router of my application to handle this change as a patch and it seems to work great.
> use cache adapter at runtime instead of compile time for PutApiSpec

- .github/workflows/release.yml
The goal of this PR is to have a GH action build and then publish a new hex.pm package version when a tag starting with `v` is pushed.
We'll still need to push a commit like e588b0febf0 to bump the version is mix.exs and update the changelog before cutting a release.
We have to set `secrets.HEX_API_KEY`.
> Build and publish a hex.pm package automatically

- README.md
- lib/open_api_spex/plug/cache.ex
- lib/open_api_spex/plug/none_cache.ex
See: https://github.com/open-api-spex/open_api_spex/issues/476
Some users might miss that there's a way to disable API spec caching and they may be restarting their app after every spec change.
> Document OpenApiSpex.Plug.NoneCache

- lib/open_api_spex/schema.ex
- test/schema_test.exs
I've noticed warnings caused by `OpenApiSpex.schema/1` which indicate that duplicated keys are passed to `defstruct` which makes impossible using `--warnings-as-errors` in CI.
```
warning: duplicate key :state found in struct
(elixir 1.13.1) lib/kernel/utils.ex:135: Kernel.Utils.warn_on_duplicate_struct_key/1
(elixir 1.13.1) lib/kernel/utils.ex:105: Kernel.Utils.defstruct/2
....:164: (module)
(elixir 1.13.1) src/elixir_compiler.erl:73: :elixir_compiler.dispatch/4
(elixir 1.13.1) src/elixir_compiler.erl:58: :elixir_compiler.compile/3
(elixir 1.13.1) src/elixir_module.erl:369: :elixir_module.eval_form/6
(elixir 1.13.1) src/elixir_module.erl:105: :elixir_module.compile/5
....: (module)
(elixir 1.13.1) src/elixir_compiler.erl:73: :elixir_compiler.dispatch/4
(elixir 1.13.1) …
```
> fix: Delete duplicated key in struct error

- lib/open_api_spex/open_api.ex
- lib/open_api_spex/plug/render_spec.ex
- lib/open_api_spex/plug/swagger_ui.ex
Fixes the following compilation warnings:
```
warning: undefined module attribute @yaml_encoder, please remove access to @yaml_encoder or explicitly set it
before access
lib/open_api_spex/open_api.ex:108: OpenApiSpex.OpenApi (module)
warning: Phoenix.Controller.endpoint_module/1 is undefined (module Phoenix.Controller is not available or is y
et to be defined)
lib/open_api_spex/plug/swagger_ui.ex:196: OpenApiSpex.Plug.SwaggerUI.supplement_config/2
```
It also fixes the following warning which appears when there's no available JSON encoder:
```
warning: nil.encode!/1 is undefined (module nil is not available or is yet to be defined)
lib/open_api_spex/plug/render_spec.ex:41: OpenApiSpex.Plug.RenderSpec.call/2
```
Resolves https://github.com/open-api-spex/open_api_spex/issues/475
> Fix compilation warnings

- lib/open_api_spex.ex
- lib/open_api_spex/cast.ex
- lib/open_api_spex/cast/object.ex
- lib/open_api_spex/cast_parameters.ex
- lib/open_api_spex/operation2.ex
- test/cast/object_test.exs
- test/cast_test.exs
- test/operation2_test.exs
Added an option to disable the auto-population of default values in casted parameters.
The configuration is optional and by default the old behaviour (populate the default values) is preserved
> Allow to configure casting to not automatically populate default values

- examples/plug_app/config/config.exs
- examples/plug_app/config/test.exs
- examples/plug_app/test/test_helper.exs
- examples/plug_app/test/user_handler_test.exs
This PR brings the following changes:
* Ensures there are no compilation warnings in examples/plug_app
* Catches warnings in CI builds
* Adds a `.formatter.exs` in examples/plug_app
> Fix mix config warnings in examples

- .formatter.exs
Similar to how ExUnit's [assert](https://hexdocs.pm/ex_unit/ExUnit.Assertions.html#assert/1) does not require parentheses we should follow the same convention for this library's test assertion functions.
> Allow omitting parens for test assertion functions

- lib/open_api_spex/open_api/decode.ex
- test/open_api/decode_test.exs
- test/support/encoded_schema.json
Schemas with a `not` keyword were not correctly decoded
> `not` schemas not correctly decoded

- mix.exs
A prior change that was merged broke usage of poison 3.0
https://github.com/open-api-spex/open_api_spex/pull/377/commits/5c0a83a7ab653a06840848cbf96960b976254727#diff-dfa6f4ed74c90e5d4fda283d547d366586e690387289bcfd473e3fa5f9ace308
This forces all users who still have incompatible apps to upgrade even though the dependency is optional.
This PR adds 3.0 back to the list, as it is a breaking change for those with dependencies in umbrellas using 3.0.
> Allow users to use poison 3.0

- lib/open_api_spex/cast.ex
- lib/open_api_spex/cast/string.ex
- test/cast/string_test.exs
- test/test_assertions_test.exs
open_api_spex already knows how to treat atoms as string-like types in enums ([example](https://github.com/open-api-spex/open_api_spex/blob/master/test/cast/enum_test.exs#L43)). 
This PR expands this behaviour to strings so that casting an atom value into a :string schema won't fail.
> Allow casting atoms as strings

- mix.exs
- mix.lock
This fixes:
- #500
Note: the `Mix.lock` file is updated to ensure tests will run on latest, but is excluded from the distribution (the file is not in the list at https://preview.hex.pm/preview/ymlr/3.0.1).
> Relax dependency constraint on ymlr

- lib/open_api_spex/cast/string.ex
- test/cast/string_test.exs
According to OpenAPI spec version 3.0, strings of format "byte" contain base64-encoded values.
For context, handling of string format has changed in 3.1, see: https://github.com/OAI/OpenAPI-Specification/pull/2200
> Implement casting of "byte" string type

- lib/open_api_spex/schema_resolver.ex
- test/schema_resolver_test.exs
- test/support/schemas.ex
fixes #387
Given a schemas such as `PetAppointmentRequest` from the test suite:
```elixir
defmodule PetAppointmentRequest do
OpenApiSpex.schema(%{
title: "PetAppointmentRequest",
description: "POST body for making a pet appointment",
type: :object,
oneOf: [
TrainingAppointment,
GroomingAppointment
],
discriminator: %OpenApiSpex.Discriminator{
propertyName: "appointment_type",
mapping: %{
"training" => TrainingAppointment,
"grooming" => GroomingAppointment
}
}
})
end
```
The `resolve_schema_modules` function will now replace modules appearing in the `discriminator.property.mapping` map, with the appropriate path to the schema, eg "#/components/schemas/TrainingAppointment".
Rendered to JSON gives:
```json
"PetAppointmentRequest": {
"description": "POST body for making a pet appointment", …
```
> Resolve schema modules in discriminator mapping

- lib/open_api_spex/open_api.ex
Noticed a validation error when the `required` array is empty.
In the json schema version used by Swagger 3.0, the required property must contain at least one item if it is present.
https://json-schema.org/understanding-json-schema/reference/object.html?highlight=required#required-properties
> Omit required from schemas when list is empty

- .github/workflows/elixir.yml
- lib/open_api_spex/cast/string.ex
- test/cast/string_test.exs
Currently trying to cast a `%Date{}` or `%DateTime{}` as a String with `format: :"date-time"` or `format: :"date"` returns a validation error.
With this PR we can improve the consistency of casting and validations by being a little more flexible in the types of inputs accepted `OpenApiSpex.Cast.String` already accepts the following non JSON or OpenAPI primitives:
* Plug.Upload
* `atoms`
A schema can be validated, casted, transformed and then validated again.
> Accept dates and datetimes in formatted string schemas

- lib/open_api_spex/path_item.ex
- lib/open_api_spex/paths.ex
Adds the missing types to `Paths.from_routes/1` `spec`. Also adds an example on how to use this function.
Fixes #527
> Fix typespec and add example to Paths.from_routes/1

- lib/open_api_spex/cast/discriminator.ex
- test/cast/discriminator_test.exs
- test/cast/one_of_test.exs
Addresses: https://github.com/open-api-spex/open_api_spex/issues/522
When we attempt to cast polymorphic (`oneOf`, `anyOf`) schemas and a `discriminator` is provided, we should be casting only the schema specified by the discriminator and any error messages should be related to that schema.
It's unclear if there is a use case for `discriminator` in conjunction with `allOf` but since the spec clearly states
>  allOf - validates the value against all the subschemas
that the input value must be validated against all the schemas, for `allOf` this PR preserves the existing behaviour.
> Keep discriminator errors relevant

- lib/open_api_spex/controller_specs.ex
It's common to pass schema structs as types for the parameters in an `operation`, like:
```elixir
operation :foo,
request_body: {"Request", "application/json", properties: %{bar: ApiSchemas.Bar}
```
Without escaping that module alias, this introduces a compile time dependency between the controller using `operation` and the schema module.
This PR fixes that. I'm not sure if this issue exists in other macros, but I think this same approach can be used in any place where this happens.
> Avoid compile time dependencies

- examples/phoenix_app/lib/phoenix_app_web/api_spec.ex
- examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller.ex
- examples/phoenix_app/lib/phoenix_app_web/controllers/user_controller_with_struct_specs.ex
- lib/open_api_spex/operation_builder.ex
- test/controller_test.exs
- test/support/api_spec.ex
- test/support/user_controller_annotated.ex
> Support passing a %Reference{} as a response when doing controller specs

- lib/open_api_spex/cast/object.ex
- test/cast/object_test.exs
Fixes #528.
Adds support for structs when `Cast` ing values. If casting succeeds the structs are preserved (i.e. not converted to maps).
> Support structs as inputs when casting objects

- mix.exs
- mix.lock
Fixes #543 
PS. I'm pretty new to Elixir, I updated the packages and ran the tests and everything seemed to be OK. Please give my contribution a quick look to make sure I didn't do anything silly. I modeled my changes based on pull request #502. Thanks for making such a great project!
> Relax dependency constraint on ymlr to allow version ~> 4.0

- .github/workflows/elixir.yml
- CHANGELOG.md
- lib/open_api_spex/cast_parameters.ex
- mix.exs
Before the fix:
```
==> open_api_spex
Compiling 99 files (.ex)
warning: Regex.regex?/1 is deprecated. Use Kernel.is_struct/2 or pattern match on %Regex{} instead
lib/open_api_spex/cast_parameters.ex:155: OpenApiSpex.CastParameters.pre_parse_parameter/3
Generated open_api_spex app
```
This PR fixes the warning.
Since the CI failed on Elixir 1.10, and it is not maintained anymore, I bumped the requirement to 1.11 & adapted the CI too.
> Fix deprecation warning on Elixir 1.15, require Elixir 1.11, adapt CI

- lib/mix/tasks/openapi.spec.json.ex
- lib/mix/tasks/openapi.spec.yaml.ex
- lib/open_api_spex/export_spec.ex
- test/mix/tasks/openapi.spec.json_test.exs
This PR adds a `--quiet` option on the spec generation task.
It allows to disable the mix shell printing when creating folders and files.
Useful to avoid pollution if you run the task in tests, for example:
> Add `--quiet` option for spec generation

- lib/open_api_spex.ex
- lib/open_api_spex/cast/utils.ex
- lib/open_api_spex/operation2.ex
- lib/open_api_spex/plug/cast.ex
- lib/open_api_spex/plug/render_spec.ex
- lib/open_api_spex/test/test_assertions.ex
- test/support/pet_controller.ex
- test/test_assertions_test.exs
This is a small proposal to add a few things to help with testing based on `operationId`s instead of _(or along side of)_ `schema_name`s. There are a few benefits to this, but the primary one is that it enforces `operationId` usage. Most organizations that deal with any type of code generation are going to most likely want to enforce operationIds.
~~I thought about just looking at the path in `conn` and resolving backwards with a method like `assert_uses_schema`, but that was a bit too 🪄 for what I wanted to achieve.~~ _(i was able to achieve this very simply by assigning the operation_id. it now supports automatic inference or manual specification)_
I'm sure I've missed something here, but very open to feedback if anyone else would benefit from this 🎉
> feat: add assert_operation_response, assert_raw_schema

- lib/open_api_spex/cast/discriminator.ex
- test/cast/discriminator_test.exs
- test/mix/tasks/openapi.spec.json_test.exs
When elements of a discriminator does not have a `title` property the cast fails. The `mapping` can indeed contain references so we can fallback to use them to retrieve the discriminator schema from `ctx.schemas`.
A part for variables renaming the main change is [this](https://github.com/open-api-spex/open_api_spex/compare/master...athonet-open:open_api_spex:fix-discriminator?expand=1#diff-7e4bf47947cd534c1229c24ddfad11146800674538e17c7533b1c7f8e18aab6bL96)
> Cast discriminator when no title present

- lib/open_api_spex/path_item.ex
- lib/open_api_spex/paths.ex
- test/paths_test.exs
We have an issue where the actions that is explicitly marked with `operation false` still show up with empty paths in the spec file. This removes the path from the spec if there are no actions specified.
I'm not sure if comparing with an empty `PathItem` is the best approach here. Please let me know if there is something better that can be used instead.
> Exclude empty paths from spec

- lib/open_api_spex/cast/utils.ex
- lib/open_api_spex/test/test_assertions.ex
- test/test_assertions_test.exs
Fixes #575.
- Modifies `Utils.content_type_from_header` to accept a header location
- Updates `assert_operation_response` to pass in `:response` to the above fn
- Simplifies error messages for schema resolution failures
> fix: assert_operation_response header lookup

- .github/workflows/elixir.yml
- mix.exs
- test/cast/object_test.exs
- test/paths_test.exs
Seems to also work with ymlr 5.0.0
Also:
- I noticed that 2 tests were failing. Maybe it's because I'm running Elixir 1.16. I tried to fix them.
- I also added more Elixir versions to the CI pipeline.
> Relax dependency constraint on ymlr to allow version ~> 5.0

- .github/workflows/elixir.yml
- test/paths_test.exs
See: https://github.com/open-api-spex/open_api_spex/issues/601
> Update Elixir version test matrix

- examples/phoenix_app/lib/phoenix_app_web/router.ex
- lib/open_api_spex/plug/swagger_ui.ex
- lib/open_api_spex/plug/swagger_ui_oauth2_redirect.ex
- test/plug/swagger_ui_test.exs
We use a strict [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) on our site which disallows inline scripts and inline styles unless they include the correct [nonce value](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce). This change allows the user to configure keys that, if given, will be used to look up nonces in the `conn.assigns` which are then used on the corresponding `<script>` and `<style>` elements.
Configuration looks like this:
```elixir
get "/swaggerui", OpenApiSpex.Plug.SwaggerUI,
...
csp_nonce_assign_key: %{script: :script_src_nonce, style: :style_src_nonce}
```
Or to use the same nonce for both:
```elixir
get "/swaggerui", OpenApiSpex.Plug.SwaggerUI,
...
csp_nonce_assign_key: :nonce
```
This configuration …
> Set nonces on <script> and <style> elements if configured

- lib/open_api_spex/operation2.ex
- lib/open_api_spex/plug/cast_and_validate.ex
- lib/open_api_spex/plug/swagger_ui_oauth2_redirect.ex
- test/support/pet_controller.ex
- test/test_assertions_test.exs
There was an issue where you had to pass in the `operationId` on error cases to `assert_operation_response` because of the nature of the error handling halting and returning a collection of errors for the given step. Lifting the `put_operation_id` up gets around all of that as even if things `halt`, we'll still have a reference to the operationId in `conn.private`
> fix: ensure operation_id is always set on conn.private

- README.md
Simple grammar fix
Thanks for the beautiful documentation, it reads very nicely
> Tiny README fix

- lib/open_api_spex/schema.ex
- test/schema_test.exs
When generating examples with `Schema.example/1` and the schema type is :string` we always return `""` which wouldn't be matching the schema if `minLength` is set and is greater than zero.
> Respect minLength when generating string examples

- lib/open_api_spex.ex
- lib/open_api_spex/cast.ex
- lib/open_api_spex/cast/object.ex
- lib/open_api_spex/cast/utils.ex
- test/cast_test.exs
`read_write_scope` is needed fort correctly handling `readOnly` and `writeOnly` required properties but it is non populated when calling directly cast functions. This adds that option.
There was also a problem when the property marked as `readOnly` or `writeOnly` is inside a reference. Before this change the   [`check_required_fields` function took as input the original `ctx` with properties not yet resolved](https://github.com/open-api-spex/open_api_spex/pull/572/files#diff-aa0035d77c1a9fcfa904c6bc5a3f8110b8e78d360a19bbaf1670767f53ad56dbL25). Now the `ctx` is updated with resolved properties and the required check works as expected. In doing so I also changed a little bit the `Object` module to make all functions modify and accept the same `ctx` making the code much more readable.
Fixes …
> Accept read_write_scope from opts when calling cast functions directly

- .github/workflows/elixir.yml
- mix.exs
See CI failure in #613 for build failure in older elixir verisons.
> chore: Drop build matrix support for elixir 1.11, 1.12, 1.13 and OTP 22

- lib/open_api_spex/inspect/for_schema.ex
- test/inspect/for_schema_test.exs
currently, inspecting an `OpenApiSpex.Schema` looks like this:
`%OpenApiSpex.Schema%{type: :object}`
with the new change, it looks like this:
`%OpenApiSpex.Schema{type: :object}`
which allows copy/pasting the struct
> improvement: use struct spec to avoid double `%` in struct inspect

- lib/mix/tasks/openapi.spec.json.ex
- lib/mix/tasks/openapi.spec.yaml.ex
- lib/open_api_spex/export_spec.ex
Add a `--check` option to run Mix tasks and compare the generated spec with a previously generated file.
This is useful for scenarios where a CI check is desirable to catch unwanted drifts from a validated OpenAPI spec: e.g. the OpenAPI spec is committed and reviewed, and should not change without additional review.
Fixes #617
> Feat: add `--check` option in Mix tasks to compare the generated spec with a previously generated file

- lib/open_api_spex/cast/error.ex
- test/cast_test.exs
> Support custom error messages in custom validators

- lib/open_api_spex/cast/integer.ex
- lib/open_api_spex/cast/number.ex
- mix.exs
- mix.lock
- test/cast/integer_test.exs
- test/cast/number_test.exs
The idea is that an application which uses [decimal](https://hexdocs.pm/decimal/Decimal) for decimals can call `OpenApiSpex.cast_value/3` directly without having to stringify any such decimals first. `decimal` is already an indirect optional dependency of open_api_spex and a very common one due to it being a dependency of `ecto`.
> Support casting decimals

- lib/open_api_spex/plug/swagger_ui.ex
> Use latest version of SwaggerUI by default, but allow it to be configured

- lib/open_api_spex/cast.ex
- test/cast_test.exs
- test/support/encoded_schema.json
Addresses https://github.com/open-api-spex/open_api_spex/issues/646
> Fix cast x-validate when decoded schema

- lib/open_api_spex/schema.ex
- test/schema_test.exs
> Add examples property to Schema

- lib/open_api_spex.ex
- lib/open_api_spex/schema_resolver.ex
- test/schema_resolver_test.exs
This PR clarifies and tests the behaviour of SchemaResolved when it encounters schema modules with the same title.
See: https://github.com/open-api-spex/open_api_spex/issues/587, https://github.com/open-api-spex/open_api_spex/issues/566
It adds the following admonition block:
When a schema module we're resolving already exists in `components.schemas` and its `x-struct` is different from the module being resolved we can log a warning. This can turn out to be very noisy this library currently logs very little.
> Document schema resolver duplicate titles behaviour

- lib/open_api_spex/test/test_assertions.ex
- test/support/api_spec.ex
- test/support/pet_controller.ex
Previously a reference response would lead to the following error.
```
Failed to resolve a response schema for operation_id: some_operation_id for status code: 404 and content type: application/json
````
This was caused by `assert_operation_response/2` not resolving references.
> Fix assert_operation_response/2 references

- lib/open_api_spex/plug/swagger_ui.ex
Currently the `OpenApiSpex.Plug.SwaggerUI` does not support multiple URLs and to preview more than a single spec one has to add the plug n times.
The SwaggerUI supports this already [docs](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/)  through the topbar plugin which is loaded in the `SwaggerUIStandalonePreset` preset open_api_spex uses.
This PR allows setting a `paths` keyword instead of a `path` string.
```elixir
scope "/" do
pipe_through :browser # Use the default browser stack
get "/", MyAppWeb.PageController, :index
get "/swaggerui", OpenApiSpex.Plug.SwaggerUI,
paths: [
latest: "/api/openapi",
legacy: "/legacy_api/openapi",
other_app: "http://localhost:4001/my_other_app/api/openapi"
]
end
```
Which renders as seen in the screenshot below:
It does not …
> Support multiple apps in Plug.SwaggerUI
